# Change these first
owner: ettelabsinc # Your GitHub organization or username, where this repository lives
repo: ette-uptimejs # The name of this repository

sites:
  - name: demo-web.prod (IPv4, HTTPS)
    url: https://demo-web.prod.dashphone.app
    ipv6: false
  - name: demo-web.prod (IPv6, HTTPS)
    url: https://demo-web.prod.dashphone.app
    ipv6: true

  - name: demo-web.staging (IPv4, HTTPS)
    url: https://stagingapp.dashphone.app
    ipv6: false
  - name: emo-web.staging (IPv6, HTTPS)
    url: https://stagingapp.dashphone.app
    ipv6: true

  - name: sip1.demo.prod (IPv4, HTTPS)
    url: https://sip1.demo.prod.dashphone.app/metrics
    ipv6: false
  - name: sip1.demo.prod (IPv6, HTTPS)
    url: https://sip1.demo.prod.dashphone.app/metrics
    ipv6: true

  - name: sip1.demo.staging (IPv4, HTTPS)
    url: https://sip1.demo.staging.dashphone.app/metrics
    ipv6: false
  - name: sip1.demo.staging (IPv6, HTTPS)
    url: https://sip1.demo.staging.dashphone.app/metrics
    ipv6: true

  - name: sip1.demo.prod (IPv4, 5060/TCP)
    url: sip1.demo.prod.dashphone.app
    port: 5060
    check: "tcp-ping"
    ipv6: false
  # - name: sip1.demo.prod (IPv6, 5060/TCP)
  #   url: sip1.demo.prod.dashphone.app
  #   port: 5060
  #   check: "tcp-ping"
  #   ipv6: true

  - name: sip1.demo.staging (IPv4, 5060/TCP)
    url: sip1.demo.staging.dashphone.app
    port: 5060
    check: "tcp-ping"
    ipv6: false
  # - name: sip1.demo.staging (IPv6, 5060/TCP)
  #   url: sip1.demo.staging.dashphone.app
  #   port: 5060
  #   check: "tcp-ping"
  #   ipv6: true

  - name: fs1.demo.prod (IPv4, 5070/TCP)
    url: fs1.demo.prod.dashphone.app
    port: 5070
    check: "tcp-ping"
    ipv6: false
  # - name: fs1.demo.prod (IPv6, 5070/TCP)
  #   url: fs1.demo.prod.dashphone.app
  #   port: 5070
  #   check: "tcp-ping"
  #   ipv6: true

  - name: fs1.demo.staging (IPv4, 5070/TCP)
    url: fs1.demo.staging.dashphone.app
    port: 5070
    check: "tcp-ping"
    ipv6: false
  # - name: fs1.demo.staging (IPv6, 5070/TCP)
  #   url: fs1.demo.staging.dashphone.app
  #   port: 5070
  #   check: "tcp-ping"
  #   ipv6: true

  - name: cr1.prod (IPv4, 5060/TCP)
    url: cr1.prod.ettelabs.com
    port: 5060
    check: "tcp-ping"
    ipv6: false
  - name: cr2.prod (IPv4, 5060/TCP)
    url: cr2.prod.ettelabs.com
    port: 5060
    check: "tcp-ping"
    ipv6: false
  - name: cr1.staging (IPv4, 5060/TCP)
    url: cr1.staging.ettelabs.com
    port: 5060
    check: "tcp-ping"
    ipv6: false
  - name: cr2.staging (IPv4, 5060/TCP)
    url: cr2.staging.ettelabs.com
    port: 5060
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.ettelabs.com
  baseUrl: /ette-uptimejs
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for Ette Labs
  introTitle: "Ette Labs"
  introMessage: "Welcome! Here we monitor some services."
  navbar:
    - title: Status
      href: /ette-uptimejs
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
